frame = "transparent"
fork = true
maximized = false
mouse-cursor-icon = "arrow"
tabs = true

# [font]
# normal = ["Maple Mono NF"]
# style = "Italic"
# size = 14
#
# [[font.italic]]
# family = "Maple Mono NF"
