# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# 主题
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'macchiato'
set -g @catppuccin_window_tabs_enabled on

run '~/.config/tmux/plugins/tpm/tpm'

# 设置顶部显示
set-option -g status-position top
set-option -g status-justify centre
# 设置tmux颜色支持
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

